### ISSUE TITLE
How we can use it in webserver?

### ISSUE THREAD

**Issue by ankur09011** [dgilland/cacheout#22]

**Comment by dgilland** [comment]
It may depend on which webserver you are using but a cacheout instance uses a dictionary under-the-hood. Typically you would have a singleton instance of the cacheout instance defined somewhere and then made accessible during web request handling. How you might do that might be influenced by the web framework but ignoring that part, just creating the instance in a module and then importing it would work.

If you are creating separate web worker processes, then just be aware that the cacheout instance from one process wouldn't have access to the cacheout data in another process. But threaded workers should be able to access the same cacheout instance so they would share data.

**Comment by ankur09011** [comment]
I am using async `FastApi` wenserver.
Using the same way having a singleton instance of the cacheout instance and using it in parts of code. The problem is I am running the server under gunicorn with `4 workers`  and every worker is maintains it own cacheout instance. Is there any any I can share that between the workers?

**Comment by dgilland** [comment]
You would need to use a data structure that can be shared between processes. That isn't something that is implemented in cacheout right now, but you could override the internals of cacheout to replace the ordered-dictionary implementation with something that works across processes.

For example, the [Manager](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.sharedctypes.multiprocessing.Manager) class has a [dict](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.managers.SyncManager.dict) method that works across processes. But then you would also need to implement the various ordered-dictionary methods that are used by cacheout as needed for whatever caching strategy you need. You would also need to start the Gunicorn server a certain way as well per https://stackoverflow.com/a/66135571/681166.

So if something like redis is available to you, then that may be a better option or some other Python library that implements multiprocess caching if you want to stick with in-memory caching without a dedicated cache server.

**Comment by ankur09011** [comment]
Thank You @dgilland for giving detailed explanation on this. Not want to have a TCP call so not going for Redis.
This is all good for the time being

**Comment by mvanderlee** [comment]
I solved this using [UltraDict](https://github.com/ronny-rentner/UltraDict)

```python
from cacheout import Cache
from UltraDict import UltraDict

class CachableUltraDict(UltraDict):
    '''Allows us to use an UltraDict for cacheout.
        This allows us to have shared cross-worker gunicorn cache!
    '''

    def copy(self):
        return self.__class__(
            self,
            name=self.name,
            buffer_size=self.buffer_size,
            serializer=self.serializer,
            shared_lock=self.shared_lock,
            full_dump_size=self.full_dump_size,
            auto_unlink=self.auto_unlink,
            recurse=self.recurse,
            recurse_register=self.recurse_register,
        )

cache = Cache()
cache._cache = CachableUltraDict()
```

**Comment by ankur09011** [comment]
@mvanderlee Thanks for this
