### ISSUE TITLE
Cache statistics

### ISSUE THREAD

**Issue by uncle-lv** [dgilland/cacheout#32]
I'm going to write the cache statistics module. Besides cache hits/misses and cache frequency, are there any statistics that need to be recorded?

I don't understand what **cache frequency** means. Does it mean the number of times a cache entry was accessed?

To-Do List:
- [x] Total cache hits
- [x] Total cache misses
- [x] Hit rate
- [x] Miss rate
- [x] Eviction rate
- [x] Total size (entity count)
- [ ] ~Total size in bytes~
- [ ] ~Average size of entities in bytes~
- [ ] ~Largest N keys~

**Comment by dgilland** [comment]
Cache frequency would be: `Cache Frequency (%) = (Cache Hits / Total Memory Accesses) * 100`

Some other potential stats:

- Cache hit time: average time it takes to access data from the cache when a cache hit occurs (may not be too useful since cacheout only has an in-memory cache so theoretically should be a constant look up time since it's using a dictionary, but still maybe useful to know)
- Cache miss penalty: average time it takes to retrieve data when a cache miss occurs (again, may not be too useful since it should also be constant but 🤷) 
- Min/avg/max/current size
- Eviction rate: `Eviction Rate (%) = (Total Cache Evictions / Total Cache Misses) * 100`

Stats should be opt-in initially since there may be some non-trivial perf/memory-overhead cost.

Also, could start with just cache hits, misses, and frequency, and add other later (no need to add them all in one go).

**Comment by uncle-lv** [comment]
I'm confused about Min/avg/max/current size.

The minimum size is always zero, because the cache is empty initially.
The maximum size is always `maxsize` after the cache has been full.
And how do I calculate avg size?

If I misunderstood it, please point it out.

**Comment by dgilland** [comment]
> I'm confused about Min/avg/max/current size.
> 
> The minimum size is always zero, because the cache is empty initially. The maximum size is always `maxsize` after the cache has been full.

🤦 I guess I didn't think that one through 😆 

Maybe just current size then, but that could be both the number of entries and the total bytes of memory.

**Comment by uncle-lv** [comment]
I think average size and maximum size is meaningful, however the minimum size can be ignored.
**average size**: `total bytes/total entries`.
**maximum size**: the maximum number of bytes occupied by an entity.

It's even better if the user can check the details of how many bytes each entity occupies, just like [bigkeys](https://redis.io/docs/ui/cli/#scanning-for-big-keys) in redis.
But it will take a lot of work. Maybe we can put it in the plan first, but we don’t necessarily have to do it right away.

**Comment by dgilland** [comment]
Agree on average size.

Maximum single size seems less important as opposed to what you mention about bigkeys where it returns the top N largest entities seems more useful.

But I also agree with keeping the first iteration smaller and iterating to additional features later once the groundwork has been laid.

**Comment by uncle-lv** [comment]
Agree. Maximum single size only can indicate to the user that there may be a big key. But if the user doesn't know which key, nothing can be done.



So the result of this discussion is as follows:

- [ ] Cache hit time
- [ ] Cache miss penalty
- [ ] Eviction rate
- [ ] Average size
- [ ] the top N biggest keys (in the future)



Is there anything else that has been missed?

**Comment by dgilland** [comment]
MVP:
- Total cache hits
- Total cache misses
- Hit rate
- Miss rate
- Eviction rate
- Total size (entity count)

Future:
- Total size in bytes
- Average size of entities in bytes
- Largest N keys

**Comment by dgilland** [comment]
Sorry, had a typo there. I think it should be total evictions divided by total accesses where evictions don't include expired keys, just the ones that were evicted due to size constraints based on the cache policy.

**Comment by uncle-lv** [comment]
It's a little hard to calculate the size of objects precisely. [`sys.getsizeof()`](https://nedbatchelder.com/blog/202002/sysgetsizeof_is_not_what_you_want.html) isn't a good choice(even wrong).

[pympler](https://github.com/pympler/pympler) is better. But it too complex for our needs. We only need the [`asizeof`](https://github.com/pympler/pympler/blob/master/pympler/asizeof.py) module(however also too complex).

There are three choices now:
- Use pympler directly
- Only use `asizeof` module
- Write our own module(according to pympler)

Any suggestions?

**Comment by dgilland** [comment]
> Any suggestions?

Based on your links, the complexity involved seems no worth it.

**Comment by dgilland** [comment]
So given the complexity involved in accurately calculating the in-memory cache size, I'd suggest punting on the bytes-related stats.

**Comment by uncle-lv** [comment]
I don't understand well, could you explain it in detail?

**Comment by uncle-lv** [comment]
> So given the complexity involved in accurately calculating the in-memory cache size, I'd suggest punting on the bytes-related stats.

I don't understand well, could you explain it in detail?

**Comment by dgilland** [comment]
Adding accurate in-memory size-in-bytes stats is too complex so let's not do it.

**Comment by uncle-lv** [comment]
> Adding accurate in-memory size-in-bytes stats is too complex so let's not do it.

What does the bytes-related stats mean?

**Comment by dgilland** [comment]
These:

* Total size in bytes
* Average size of entities in bytes
* Largest N keys

**Comment by uncle-lv** [comment]
Completed in #34
