### ISSUE TITLE
on-get callback

### ISSUE THREAD

**Issue by uncle-lv** [dgilland/cacheout#36]
I think `on_get` callback may just be simple like this:
```python
cache = Cache(on_get=on_get)
```

The callback function.
```python
Callable[[key: Hashable, value: Any],  None]
```

In fact, I've hardly ever seen a on-get listener in cache libraries. Do we really need it? 🤷

**Comment by dgilland** [comment]
I'm also not sure on the utility of it, but the callback could also include whether the key there or not. That might make it a little more useful.

**Comment by uncle-lv** [comment]
> I'm also not sure on the utility of it, but the callback could also include whether the key there or not. That might make it a little more useful.

If the key is missed, whichever is better is to set the `value` to None or `UNSET`?

**Comment by dgilland** [comment]
> If the key is missed, whichever is better is to set the `value` to None or `UNSET`?

Another question around this would be whether having `value` always be the returned value (i.e. the existing value or the default value) and send another variable to indicate whether the key exists would be preferable over having the `value` only ever be the existing one. Potentially the default value could come from a default function so would having that `value` potentially be useful? Seems like we'd have more information with the first option.

**Comment by uncle-lv** [comment]
> > If the key is missed, whichever is better is to set the `value` to None or `UNSET`?
> 
> Another question around this would be whether having `value` always be the returned value (i.e. the existing value or the default value) and send another variable to indicate whether the key exists would be preferable over having the `value` only ever be the existing one. Potentially the default value could come from a default function so would having that `value` potentially be useful? Seems like we'd have more information with the first option.

```python
Callable[[key: Hashable, value: Any, existed: bool],  None]
```

Add `existed` to indicate whether the key has existed. If `existed` is true, `value` is the real value. Otherwise, `value` is the default value.

**Comment by dgilland** [comment]
> Callable[[key: Hashable, value: Any, existed: bool],  None]
> Add existed to indicate whether the key has existed. If existed is true, value is the real value. Otherwise, value is the default value.

👍

**Comment by dgilland** [comment]
Done in #38
