### ISSUE TITLE
 single key info

### ISSUE THREAD

**Issue by silencesmile** [dgilland/cacheout#7]
1、How to get a single key and how long it will expire 
2、How to extend the expiration time of a single key

**Comment by dgilland** [comment]
> 1、How to get a single key

Do you mean fetching the key value?

```python
cache = cacheout.Cache()
value = cache.get(key)
```

> and how long it will expire

```python
expires_on = cache.expire_times.get(key)
# will be seconds from epoch
```

> 2、How to extend the expiration time of a single key

You can set the key again to give it a key expiration.

```python
value = cache.get(key)
if value is not None:
    cache.set(value)
    # Or with custom expiration
    cache.set(key, value, ttl=expiration)
```

There currently isn't a more formal way to do this with a single `Cache` method but you could subclass `Cache` if you wanted to encapsulate that logic. This kind of functionality could be added to `Cache` directly if there's a strong desire for it (e.g. I could see there being a method that sets the expiration of an existing key with the default ttl or a custom one and a method that could extend the key by a given amount [i.e. current expiration += offset]).
